apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: "36.*"
    releaseName: traefik
    namespace: ingress
    valuesFile: values.yaml
