apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "127.0.0.1"
        searches: []
        options:
          - name: ndots
            value: "0"
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]
          ports:
            - containerPort: 8388
              name: socks5
            - containerPort: 8888
              name: http-proxy
            - containerPort: 9999
              name: health
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "protonvpn"
            - name: VPN_TYPE
              value: "wireguard"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_PROVIDER
              value: "protonvpn"
            - name: PORT_FORWARD_ONLY
              value: "on"
            - name: FIREWALL
              value: "on"
            - name: FIREWALL_INPUT_PORTS
              value: "8388,8888,9999"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.42.0.0/15"
            - name: HTTPPROXY
              value: "on"
            - name: HTTPPROXY_LISTENING_ADDRESS
              value: ":8888"
            - name: SHADOWSOCKS
              value: "off"
            - name: SOCKS5
              value: "on"
            - name: SOCKS5_LISTENING_ADDRESS
              value: ":8388"
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: wireguard-private-key
                  key: WIREGUARD_PRIVATE_KEY
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: tun-device
              mountPath: /dev/net/tun
            - name: gluetun-config
              mountPath: /gluetun
          readinessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 5
      volumes:
        - name: tun-device
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: gluetun-config
          persistentVolumeClaim:
            claimName: gluetun-config-pvc